---
abstract: 'combine DoCoMoGUID::RedirectFilter and DoCoMoGUID::HTMLStickyQuery.'
author:
  - 'Keiji Yoshimi <walf443 at gmail dot com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTML::TreeBuilder::XPath: 0
  HTTP::Request: 0
  Module::Install::ReadmeFromPod: 0
  Plack::Test: 0
  Test::LoadAllModules: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-DoCoMoGUID
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::StickyQuery::DoCoMoGUID: 0
  Plack::Middleware: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/walf443/p5-plack-middleware-docomoguid.git
version: 0.06
